spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/guestbook_app?useSSL=false"
    username: "root"
    password: "root"
  servlet:
    multipart:
      enabled: "false"

  # App config
server:
  port: "8080"
  application:
    name: "Guest Book API"